### ISSUE TITLE
Is there any plans for supporting filterString in ScannerOpenWithStopRequestMessage?

### ISSUE THREAD

**Issue by send2vinnie** [gridsum/NHBaseAPI#1]
Just found this .Net based HBase client library but it still lacks of some features such as filters. It there any plan and timeline for supporting them?

**Comment by g0194776** [comment]
obviously yes, BUT it was not including in current milestone.
we're going to plans the next milestone of features.
we have not concrete time for releasing next version yet, BUT
it'll be coming soon before 1st Oct.
