### ISSUE TITLE
Socket disconnected by remote server (Thrift server)

### ISSUE THREAD

**Issue by send2vinnie** [gridsum/NHBaseAPI#2]
Does NHBaseAPI work with HBase 0.94? I found it always encounters the following error while using HTable.NewScanner() to do the query:

System.Net.Sockets.SocketException (0x80004005):  An existing connection was forcibly closed by the remote host.
   in System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   in KJFramework.Net.Channels.Receivers.TcpAsynDataRecevier.Stop()

**Comment by DexterL** [comment]
We developed NHBaseAPI with HBase v1.0. It was not clear why this happened. Could you update the HBase version and try it again?

**Comment by g0194776** [comment]
Another one reason about what you happened is that the remote server rejected your TCP connection initiatively. Maybe the remote server had been detected wrong network protocol format. BUT it needs more evidences by network sniffer.

Would you like to offer network sniffer to help us finding out the reason?
